name: Test & Deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout & clone repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: test_db
          postgresql user: test_user
          postgresql password: test_password

      - name: Install dependencies
        run: npm i

      - name: Run all tests
        run: PGDATABASE=test_db PGUSER=test_user PGPASSWORD=test_password npm t
